services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    command: make dev
    environment:
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: host.docker.internal

  caddy:
    depends_on:
      app:
        condition: service_started
    image: caddy:latest
    restart: unless-stopped
    volumes:
      - ./services/caddy:/etc/caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
