services:
  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    command: make dev
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}

  caddy:
    depends_on:
      app:
        condition: service_started
    image: caddy:2.10
    restart: unless-stopped
    volumes:
      - ./services/caddy:/etc/caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
